### ISSUE TITLE
Polling option for status register

### ISSUE THREAD

**Issue by angrest** [JVKran/Forced-BME280#12]
other libraries offer a function to poll the status register to check if the measurement has started and terminated.
It would be good if a similar function would be provided. This might look like

        bool ForcedClimate::isMeasuring() {
	        uint8_t status = 0;
	        bus.beginTransmission(address);
	        bus.write((uint8_t)registers::STATUS);
	        bus.endTransmission();

	        bus.requestFrom(address,(uint8_t)1);
	        while ( bus.available() ) {
		        status = bus.read(); // receive a byte 
	        }

	        return(status & (1<<3)); //return true  in case the measuring bit (3) is set 
        }

**Comment by JVKran** [comment]
Hi @angrest,

Thanks for pointing this functionality out, appreciated. However, this library uses the BME280 in forced mode, without oversampling. That means the measurement is immediately executed and returned. Conform appendix B in [the datasheet](https://www.mouser.com/datasheet/2/783/BST-BME280-DS002-1509607.pdf) at page 52, this takes 10 milliseconds and thus, requires no delay of some kind.

Unless there's a reason for using the function above that I'm not aware of, I think it'll only confuse users.

Kind regards,

Jochem

**Comment by angrest** [comment]
Good morning, @JVKran, 
thank you for the quick response.
From the timings I measure in my sample sketch, the response from the sensor is nearly immediately available (2-5ms)

          long startTime = millis();
          mySensor.takeForcedMeasurement(); //Wake up sensor and take reading

 
           //    while (mySensor.isMeasuring() == false) {cyclesToStart++;}; //Wait for sensor to start measurement
          Serial.println("Waiting for measurement");
          //    while (mySensor.isMeasuring() == true) {cyclesToStop++;}; //Hang out while sensor completes the reading

          float hum = mySensor.getRelativeHumidity();
          float temp = mySensor.getTemperatureCelcius();
          float pres = mySensor.getPressure() * 100;

          long endTime = millis();
          Serial.print("Measure time(ms): ");
          Serial.println(endTime - startTime);

If I uncomment the call to the (now corrected code) in my first post, the total time goes up to the expected 10-12ms. The time is entirely spent in the second while-loop, typically 12-13 iterations.

From that I would conclude that waiting for the bit to be set is actually necessary. I suppose otherwise, the data from the previous measurement is being returned.
