### ISSUE TITLE
change the default I2C address in ESP32

### ISSUE THREAD

**Issue by spairo1741** [JVKran/Forced-BME280#8]
how to change the default I2C address in ESP32-cam, e.g.
for something like that
// BME280
#define I2C_SDA 3 // for ESP32-CAM
#define I2C_SCL 16
TwoWire I2CBME = TwoWire (1);
Adafruit_BME280 bme;

**Comment by JVKran** [comment]
Hi @spairo1741,

You can specify the I2C address in the constructor like underneath, where ```0x76``` is to be replaced with the desired address. The same goes for the bus; ```Wire``` can be replaced with another instance connected to other pins.

```ForcedClimate climateSensor = ForcedClimate(Wire, 0x76);```

One thing to note though, you're using Adafruit_BME280, not this library. Hence, the method above only works when using the library in this repository. 

Kind regards,

Jochem

**Comment by spairo1741** [comment]
by default i2c is pins 21 and 22 in esp32.
I have to change them to the other SDA 3 GPIO and SCL GPIO 16 because I use esp32-cam there are no pins 21 and 22 led out.
that's the problem.

**Comment by JVKran** [comment]
Hi @spairo1741 

I understand. As I've said; Wire can be replaced with another instance connected to other pins. This can be done like underneath.

``` cpp
ForcedClimate climateSensor = ForcedClimate(Wire, 0x76, false); 	// At top
Wire.begin(SDA_PIN, SCL_PIN);		// In setup()
```

That functionality is part of the Wire library.

Kind regards,

Jochem

**Comment by spairo1741** [comment]
thanks for this, working. great library.

**Comment by JVKran** [comment]
No problem. Glad to be of help and good to hear. 👍
